<?php

/**
 * BasegbUpdate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $content
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method string      getContent() Returns the current record's "content" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method gbUpdate    setUserId()  Sets the current record's "user_id" value
 * @method gbUpdate    setContent() Sets the current record's "content" value
 * @method gbUpdate    setUser()    Sets the current record's "User" value
 * 
 * @package    gesichtbuch
 * @subpackage model
 * @author     Stefan Koopmanschap
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasegbUpdate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gb_update');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}