<?php

/**
 * gbFriendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class gbFriendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object gbFriendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('gbFriend');
    }

    public function getFriendsForUser(sfGuardUser $user)
    {
      return $this->createQuery('f')->where('f.friend_id = ?', $user->getId())->execute();
    }

}