<?php

/**
 * gbUpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class gbUpdateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object gbUpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('gbUpdate');
    }

    public function getUpdatesForHomepage()
    {
        return $this->createQuery('u')
                    ->orderBy('created_at DESC')
                    ->execute();
    }
}