<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/09 16:57:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=gesichtbuch',
  'username' => 'root',
  'password' => 'secret',
  'name' => 'doctrine',
)),);
