<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/10/09 16:57:12
$this->addCache($moduleName, '_list', array('withLayout' => false, 'lifeTime' => 5, 'clientLifeTime' => 5, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

