<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/10/11 12:05:26
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

